/**
 * @file Scheduler.h
 * @brief FreeRTOS Task Scheduler Interface
 *
 * *** READ ONLY - DO NOT MODIFY ***
 *
 * This file provides the interface for initializing and managing
 * FreeRTOS tasks. All user configuration should be done in Scheduler_Cfg.h
 *
 * @warning DO NOT EDIT THIS FILE - Edit Scheduler_Cfg.h instead
 */

#ifndef SCHEDULER_H
#define SCHEDULER_H

#include <stdint.h>
#include <stdbool.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

// Include user task configuration
#include "Scheduler_Cfg.h"

// ============================================================================
// PUBLIC API FUNCTIONS
// ============================================================================

/**
 * @brief Execute all initialization functions from Init_Functions array
 */
void Scheduler_ExecuteInit(void);

/**
 * @brief Initialize the scheduler and create all configured tasks
 *
 * This function creates FreeRTOS tasks for all handlers from Task_Configurations array
 *
 * @return true if initialization successful
 * @return false if initialization failed
 */
bool Scheduler_Init(void);

/**
 * @brief Start the FreeRTOS scheduler
 *
 * @note In Arduino ESP32 Core 3.x, scheduler is already running
 */
void Scheduler_Start(void);

/**
 * @brief Get scheduler uptime in milliseconds
 *
 * @return uint32_t Uptime in milliseconds
 */
uint32_t Scheduler_GetUptime(void);

/**
 * @brief Get task handle by name
 *
 * @param task_name Task name to search for
 * @return TaskHandle_t Task handle, or NULL if not found
 */
TaskHandle_t Scheduler_GetTaskHandle(const char *task_name);

/**
 * @brief Print task statistics (stack usage, etc.)
 */
void Scheduler_PrintTaskStats(void);

/**
 * @brief Execute all functions in a task function array
 * @param function_array Pointer to NULL-terminated function pointer array
 */
void Scheduler_ExecuteFunctions(TaskFunctionPtr_t *function_array);

#endif // SCHEDULER_H